#!/usr/bin/awk -f

BEGIN{
    #inicializace promenych
    FS = "[][]| |/|-|:"
    OFS = ""
    O = 0
    I = 0
    U = 0
    T = 0
    H = 0
    time = 00
}
{
    # pokud doslo ke zmene casu, vypis hodnoty
    if($7 != time){
        print "[",$4,"/",$3,"/",$2,"-",$5,":",$6,":",time,"] ",O," ",I," ",U," ",T," "H
    }
    # aktualizuj cas
    time = $7
}
# zmen merene hodnoty
$11 == "O"{O = $14}
$11 == "I"{I = $14}
$11 == "U"{U = $14}
$11 == "T"{T = $13}
$11 == "heat"{
    if($12 == "on"){
        H = 1
    } else {
        H = 0
    }
}
END{
    #vypise posledni zaznam
    print "[",$4,"/",$3,"/",$2,"-",$5,":",$6,":",time,"] ",O," ",I," ",U," ",T," "H
}