#!/bin/bash

curl https://www.cnb.cz/cs/financni-trhy/devizovy-trh/kurzy-devizoveho-trhu/kurzy-devizoveho-trhu/ > kurzy_cnb.html 2>/dev/null

./cnb kurzy_cnb.html > kurzy_cnb_parsed.txt

rm kurzy_cnb.html

curl http://www.cnb.cz/cs/financni_trhy/devizovy_trh/kurzy_devizoveho_trhu/denni_kurz.txt > kurzy_cnb.txt 2>/dev/null

cmp kurzy_cnb_parsed.txt kurzy_cnb.txt && echo "soubory se shoduji"
